[theme]
primaryColor = "#1d3557"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f1faee"
textColor = "#1d3557"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
